FROM accetto/ubuntu-vnc-xfce-firefox-g3:latest

RUN sudo -S apt install -y wget

# For C++ 
RUN wget https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2021-03/R/eclipse-cpp-2021-03-R-linux-gtk-x86_64.tar.gz \
	&& cp eclipse-cpp-2021-03-R-linux-gtk-x86_64.tar.gz /home/headless

RUN sudo -S apt-get update \
    && sudo -S apt install -y build-essential libpci-dev libwebkit2gtk-4.0-dev

RUN cd /home/headless/ \
	&& tar -zxvf eclipse-cpp-2021-03-R-linux-gtk-x86_64.tar.gz
